swsnu/swppfall2022-team5

frontend/jest.config.js
frontend/jest.setup.js
frontend/tests/unit/index.test.ts
frontend/tests/unit/index.test.tsx

- https://stackoverflow.com/a/70646125/9046780
- https://github.com/vercel/next.js/tree/canary/examples/with-jest

🚧 Fix jest error with`useRouter`

---

backend/src/main/kotlin/com/swpp/footprinter/config/SecurityConfig.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/api/FootprintController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/dto/FootprintRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/dto/FootprintResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/model/Footprint.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/repository/FootprintRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/service/FootprintService.kt
backend/src/main/resources/application.yaml

Backend design 문서 바탕으로 footprint api를 만들었습니다.

✨ Implement Footprint API

---

backend/src/main/kotlin/com/swpp/footprinter/common/exception/FootprinterExceptionHandler.kt
backend/src/main/kotlin/com/swpp/footprinter/common/utils/Iso8601Util.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/dto/FootprintRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/dto/FootprintResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/model/Footprint.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/service/FootprintService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/photo/dto/PhotoRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/photo/dto/PhotoResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/photo/model/Photo.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/photo/service/PhotoService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/dto/PlaceRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/dto/PlaceResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/model/Place.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/repository/PlaceRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/service/externalAPI/KakaoAPIService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/tag/dto/TagResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/tag/model/Tag.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/tag/repository/TagRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/api/TraceController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/dto/TraceDetailResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/dto/TraceResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/Trace.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/api/UserController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/service/UserService.kt
backend/src/main/kotlin/com/swpp/footprinter/test/DataInitializer.kt

특정 User의 Trace를 요청하는 API를 추가했습니다

✨ Implement user trace API

---

backend/src/main/kotlin/com/swpp/footprinter/domain/place/api/PlaceController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/tag/controller/TagController.kt

✨ Added Api For Getting Tags Information

---

.github/workflows/test.yaml
README.md
backend/build.gradle.kts
backend/src/main/kotlin/com/swpp/footprinter/domain/place/service/externalAPI/KakaoAPIService.kt
frontend/jest.config.js
frontend/tests/unit/footprints.tsx/index.test.tsx
sonar-project.properties

Coveralls의 parallel build를 위해 기존 gradle plugin을 살짝 변형한 custom plugin을 build script에 직접 추가했습니다.

:construction_worker: Implement custom Jacoco Coveralls plugin

---

README.md
frontend/jest.config.js
frontend/tests/unit/footprints.tsx/index.test.tsx

Jest coverage configuration을 설정했습니다.

✅ Add frontend tests

---

backend/src/main/kotlin/com/swpp/footprinter/domain/place/model/Place.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/tag/model/Tag.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/model/User.kt
backend/src/test/kotlin/com/swpp/footprinter/global/TestHelper.kt

TestHelper 클래스를 따로 정의해놓으면 테스트 작성 시 편할 거 같아서 이부분만 PR 먼저 올립니다..!

🔨 Add TestHelper (Backend)

---

frontend/components/buttons/FloatingButton.tsx
frontend/components/buttons/RectangleButton.tsx
frontend/components/footprint/FootprintPreview.tsx
frontend/tests/unit/api/index.test.ts
frontend/tests/unit/components/FootprintsNotFound.test.tsx
frontend/tests/unit/components/FootprintsPreview.test.tsx
frontend/tests/unit/components/FullCalendar.test.tsx
frontend/tests/unit/footprints/create/index.test.tsx

🧪 Improve frontend coverage

---

frontend/__mocks__/react-kakao-maps-sdk/index.tsx
frontend/components/map/KakaoMap.tsx
frontend/pages/footprints/detail/[footprintId].tsx
frontend/tests/unit/components/FootprintCreate.test.tsx
frontend/tests/unit/footprints/detail/index.test.tsx

Improve frontend coverage

---

backend/src/main/kotlin/com/swpp/footprinter/common/model/BaseEntity.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/api/TraceLikeController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/dto/TraceLikeResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/Trace.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/TraceLike.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceLikeRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceLikeService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceService.kt
backend/src/test/kotlin/com/swpp/footprinter/domain/trace/service/TraceLikeTest.kt
backend/src/test/kotlin/com/swpp/footprinter/domain/trace/service/TraceServiceTest.kt

✨ Implement Trace Like

---

backend/src/main/resources/application.yaml
frontend/components/buttons/IconButton.tsx
frontend/components/calendar/MonthDropdown.tsx
frontend/components/containers/DropdownMenuContainer.tsx
frontend/components/containers/TransitionContainer.tsx
frontend/components/footprint/FootprintCreate.tsx
frontend/components/footprint/FootprintPreview.tsx
frontend/components/navbar/MenuDropdown.tsx
frontend/components/navbar/NavigationBar.tsx
frontend/components/placeholder/FootprintsNotFound.tsx
frontend/components/placeholder/TracesNotFound.tsx
frontend/components/textfield/TextArea.tsx
frontend/components/textfield/TextField.tsx
frontend/components/trace/TracePreview.tsx
frontend/components/upload-footprint/UploadModal.tsx
frontend/components/user/UserDropdown.tsx
frontend/components/user/UserProfile.tsx
frontend/dto/exception.ts
frontend/pages/index.tsx
frontend/pages/signin/index.tsx
frontend/pages/traces/detail/[traceId].tsx
frontend/pages/user/[username].tsx
frontend/store/auth.ts

프론트엔드 코드 리팩토링을 진행하고, 전반적인 디자인을 업데이트했습니다.

🎨 Improve frontend design

---

backend/build.gradle.kts
backend/src/main/kotlin/com/swpp/footprinter/common/Constants.kt
backend/src/main/kotlin/com/swpp/footprinter/config/QueryDslConfig.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/api/TraceController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/dto/TraceSearchRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/Trace.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceService.kt

- Trace Entity에서 public이름이 QueryDSL과 충돌이 일어나는거 같아서 이 필드를 show로 이름을 변경하였습니다.
```Json
{
"users": [
{"username": "g"}
],
"tags": [
3, 4
],
"dates": [
"2021-08-15"
],
"places": [
{
"name": "현미네조개구이",
"address": "인천 중구 덕교동 98-4"
}
]
}
```
- 비어있는 list일 경우 그 조건에 대하여 검색 없이 (모두 가져오도록) 하였습니다.

✨Implemented Search Traces with user, date, place, tag (Backend)

---

backend/src/main/kotlin/com/swpp/footprinter/domain/place/api/PlaceController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/service/PlaceService.kt

- /api/v1/place/search를 POST 로 변경하였습니다.
- search 시, 비어있는 tagIDs이 들어오면 모든 tag에 해당하는 검색결과를 반환하도록 수정하였습니다.

💥 Change place search (backend)

---

backend/src/test/kotlin/com/swpp/footprinter/domain/user/service/UserServiceTest.kt

✅ Fixed Backend Test

---

frontend/components/trace/TracePreviewTitle.tsx
frontend/tests/unit/api/index.test.ts

✅ Add frontend api test

---

frontend/pages/signin/index.tsx
frontend/tests/unit/components/FootprintCreate.test.tsx
frontend/tests/unit/components/FootprintsPreview.test.tsx
frontend/tests/unit/footprints/signin/index.test.tsx

🧪 Frontend render test for sign in

---

frontend/tests/unit/components/UserProfile.test.tsx
frontend/tests/unit/traces/explore/index.test.tsx

🧪  Add Explore, UserProfile Test

---

frontend/.ebignore
frontend/.env.production
frontend/components/trace/TracePreview.tsx
frontend/package.json
frontend/yarn.lock

- S3 API KEY 바꾸고 배포되면 image 에러 안뜨는지 확인해보면 될것같아요.

:closed_lock_with_key: https 연결, Image 오류 수정

---

frontend/.eslintrc.json
frontend/pages/signin/index.tsx

🩹 Fix infinite loop

---

frontend/components/upload-footprint/UploadModal.tsx
frontend/package.json
frontend/yarn.lock

- 이미지 압축 플러그인을 추가했습니다.
- 502 문제가 해결되길 바라며...

⚡️ Compress image before upload

---

frontend/.eslintrc.json
frontend/components/footprint/Photo.tsx
frontend/components/trace/TracePreview.tsx
frontend/components/trace/TracePreviewTitle.tsx
frontend/components/upload-footprint/UploadModal.tsx
frontend/components/user/ProfilePhoto.tsx
frontend/pages/user/[username].tsx

- 결국 next `Image`를 사용하지 않는 쪽으로 변경했습니다. (t2.micro의 한계?)

Replace Image with img

---

backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/service/FootprintService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/model/Place.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/place/service/PlaceService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceLikeRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/model/User.kt

Footprint를 삭제할 때 연관되어 있는 Trace, Place 테이블 또한 상태를 변경하도록 수정하였습니다.

🐛 Fixed Buggy Delete Footprint (Backend)

---

backend/src/main/kotlin/com/swpp/footprinter/domain/place/service/PlaceService.kt
backend/src/test/kotlin/com/swpp/footprinter/domain/place/service/PlaceServiceTest.kt

- Test Session에서 장소 검색이 잘 안된다는 피드백이 많았어서 기존 장소검색 시 지정해둔 5개 태그에 대해서만 장소 검색 결과가 나오는 것에서 태그 관계없이 가까운 순으로 모든 장소가 검색되도록 변경하였습니다.

👔 Improve Place Search (Backend)

---

backend/src/main/kotlin/com/swpp/footprinter/domain/auth/api/AuthController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/Trace.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/api/UserController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/dto/UserModifyRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/dto/UserResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/model/User.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/service/UserFollowService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/service/UserService.kt
backend/src/test/kotlin/com/swpp/footprinter/domain/trace/service/TraceServiceTest.kt
backend/src/test/kotlin/com/swpp/footprinter/domain/user/service/UserServiceTest.kt
backend/src/test/kotlin/com/swpp/footprinter/global/TestHelper.kt

```kotlin
data class UserModifyRequest(
@field: NotEmpty
val password: String,
val imagePath: String? = null,
)
```
```kotlin
data class UserResponse(
val username: String,
val followingCount: Int,
val followerCount: Int,
val traceCount: Int,
val imageUrl: String? = null,
)
```

✨Implement User profile image, and modifying profile. (Backend)

---

backend/src/main/kotlin/com/swpp/footprinter/domain/photo/api/PhotoController.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/photo/service/PhotoService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/dto/UserModifyRequest.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/user/service/UserService.kt
backend/src/main/resources/application.yaml
frontend/api/index.ts
frontend/components/upload-footprint/UploadModal.tsx
frontend/components/user/ProfilePhoto.tsx
frontend/components/user/UserProfile.tsx
frontend/package.json
frontend/pages/traces/detail/[traceId].tsx
frontend/yarn.lock

- 유저 프로필 사진 업데이트할 수 있도록 프론트엔드 구현했고 백엔드 일부 수정했습니다.

📷  Enable user profile update

---

backend/src/main/kotlin/com/swpp/footprinter/domain/trace/dto/TraceDetailResponse.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/model/Trace.kt
frontend/api/index.ts
frontend/components/footprint/PlaceSearchBox.tsx
frontend/components/trace/TracePreviewTitle.tsx
frontend/components/user/ProfilePhoto.tsx
frontend/dto/trace.ts
frontend/pages/footprints/create/index.tsx
frontend/pages/traces/explore/index.tsx

- Trace 생성할 때 제목도 같이 보내도록 변경
- 비공개/공개 여부 선택할 수 있음
- Trace 검색 기능 구현 (프론트만)

✨ 검색 기능 구현 등

---

backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/repository/FootprintRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/footprint/service/FootprintService.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/repository/TraceRepository.kt
backend/src/main/kotlin/com/swpp/footprinter/domain/trace/service/TraceService.kt
backend/src/main/resources/application.yaml
backend/src/test/kotlin/com/swpp/footprinter/domain/trace/service/TraceServiceTest.kt

Could get all other user's traces 부분이 실제 동작 테스트해보면 잘 되는데 왜 테스트코드에서만 안되는걸까요...
일단 이부분 테스트만 주석으로 바꾸어놓았습니다...

⚡️ Improve Get Queries
